export const credits = [{
    
        "cast": [
          {
            "adult": false,
            "gender": 1,
            "id": 974169,
            "known_for_department": "Acting",
            "name": "Jenna Ortega",
            "original_name": "Jenna Ortega",
            "popularity": 376.657,
            "profile_path": "/q1NRzyZQlYkxLY07GO9NVPkQnu8.jpg",
            "character": "Wednesday Addams / Goody Addams",
            "credit_id": "60a5553b9a9e20006f6079e9",
            "order": 0
          },
          {
            "adult": false,
            "gender": 1,
            "id": 2604515,
            "known_for_department": "Acting",
            "name": "Emma Myers",
            "original_name": "Emma Myers",
            "popularity": 84.35,
            "profile_path": "/e5eTDKstLsUKKfmwgiJsDakcvly.jpg",
            "character": "Enid Sinclair",
            "credit_id": "637e404385b105008f4e3e52",
            "order": 1
          },
          {
            "adult": false,
            "gender": 1,
            "id": 2189049,
            "known_for_department": "Acting",
            "name": "Joy Sunday",
            "original_name": "Joy Sunday",
            "popularity": 35.371,
            "profile_path": "/fTajkqbVGMU4O2LMteuYlffhfJI.jpg",
            "character": "Bianca Barclay",
            "credit_id": "637e4055514c4a00878820ab",
            "order": 2
          },
          {
            "adult": false,
            "gender": 2,
            "id": 1477961,
            "known_for_department": "Acting",
            "name": "Percy Hynes White",
            "original_name": "Percy Hynes White",
            "popularity": 72.717,
            "profile_path": "/hOS1vYWvTTXugOWhAGXoBH7dGHN.jpg",
            "character": "Xavier Thorpe",
            "credit_id": "637e402a6e938a00cd0030d1",
            "order": 3
          },
          {
            "adult": false,
            "gender": 2,
            "id": 1911865,
            "known_for_department": "Acting",
            "name": "Hunter Doohan",
            "original_name": "Hunter Doohan",
            "popularity": 105.021,
            "profile_path": "/79qnxlyxfRiKhN7BJoCPR9jDrfT.jpg",
            "character": "Tyler Galpin",
            "credit_id": "637e4015a410c800c8839f20",
            "order": 4
          },
          {
            "adult": false,
            "gender": 1,
            "id": 1011904,
            "known_for_department": "Acting",
            "name": "Gwendoline Christie",
            "original_name": "Gwendoline Christie",
            "popularity": 78.729,
            "profile_path": "/kmlv5i02n3zKryBr2W3kSeWVKTD.jpg",
            "character": "Larissa Weems",
            "credit_id": "614220069a3c490043d0f2b5",
            "order": 5
          },
          {
            "adult": false,
            "gender": 1,
            "id": 453,
            "known_for_department": "Acting",
            "name": "Riki Lindhome",
            "original_name": "Riki Lindhome",
            "popularity": 52.579,
            "profile_path": "/kJAGFp0ZW5sY0NoysFZcfSRykZa.jpg",
            "character": "Valerie Kinbott",
            "credit_id": "637e3fc9514c4a007f5b867d",
            "order": 6
          },
          {
            "adult": false,
            "gender": 2,
            "id": 79079,
            "known_for_department": "Acting",
            "name": "Jamie McShane",
            "original_name": "Jamie McShane",
            "popularity": 16.716,
            "profile_path": "/wojvRZMpAwytyoFTMFOpvZ26qJq.jpg",
            "character": "Donovan Galpin",
            "credit_id": "637e3ffe85b105008773eeb3",
            "order": 7
          },
          {
            "adult": false,
            "gender": 0,
            "id": 3235624,
            "known_for_department": "Acting",
            "name": "Moosa Mostafa",
            "original_name": "Moosa Mostafa",
            "popularity": 8.151,
            "profile_path": "/tEj3KXiy4dBdhFkq6NMi6BXURmQ.jpg",
            "character": "Eugene Otinger",
            "credit_id": "6381d680a410c800a4328587",
            "order": 8
          },
          {
            "adult": false,
            "gender": 1,
            "id": 6886,
            "known_for_department": "Acting",
            "name": "Christina Ricci",
            "original_name": "Christina Ricci",
            "popularity": 121.029,
            "profile_path": "/m2cY5Er1loPgHkZYdFMEz6YeiwG.jpg",
            "character": "Marilyn Thornhill",
            "credit_id": "637e40902222f600de336aab",
            "order": 9
          },
          {
            "adult": false,
            "gender": 2,
            "id": 1908241,
            "known_for_department": "Acting",
            "name": "Georgie Farmer",
            "original_name": "Georgie Farmer",
            "popularity": 43.916,
            "profile_path": "/r3AC3MDS81mWAsxoVNCSi8trLiP.jpg",
            "character": "Ajax Petropolus",
            "credit_id": "637e4068514c4a007f5b86db",
            "order": 10
          },
          {
            "adult": false,
            "gender": 1,
            "id": 2899293,
            "known_for_department": "Acting",
            "name": "Naomi J. Ogawa",
            "original_name": "Naomi J. Ogawa",
            "popularity": 11.46,
            "profile_path": "/iTPXpPNtJMv32Xnh2E4OUnBGoAE.jpg",
            "character": "Yoko Tanaka",
            "credit_id": "6381da5fa4af8f007eed4e4e",
            "order": 11
          }
        ],
        "crew": [
          {
            "adult": false,
            "gender": 2,
            "id": 1589118,
            "known_for_department": "Production",
            "name": "Steve Stark",
            "original_name": "Steve Stark",
            "popularity": 1.4,
            "profile_path": null,
            "credit_id": "61119b4201e4d1002ecac0dc",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 531,
            "known_for_department": "Sound",
            "name": "Danny Elfman",
            "original_name": "Danny Elfman",
            "popularity": 5.133,
            "profile_path": "/bcpur9bF56nLxzFzZowipA2wZhy.jpg",
            "credit_id": "61bc11a328d7fe0087b6ba2b",
            "department": "Sound",
            "job": "Original Music Composer"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 18924,
            "known_for_department": "Writing",
            "name": "Alfred Gough",
            "original_name": "Alfred Gough",
            "popularity": 7.872,
            "profile_path": "/vzIbjeI1quQTFpxOR5wEyEHddgN.jpg",
            "credit_id": "602e00cda61de1004161a078",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 18923,
            "known_for_department": "Writing",
            "name": "Miles Millar",
            "original_name": "Miles Millar",
            "popularity": 9.689,
            "profile_path": "/isLcN8MJ3ARpmTwoGtqRQsVwJqx.jpg",
            "credit_id": "602e00ddad87f7003e937387",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 510,
            "known_for_department": "Directing",
            "name": "Tim Burton",
            "original_name": "Tim Burton",
            "popularity": 20.009,
            "profile_path": "/oWZDgLRr4zgRiJEsOAtgntPd5bI.jpg",
            "credit_id": "602e00e7d55c3d003f1eeedc",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 1,
            "id": 168383,
            "known_for_department": "Writing",
            "name": "Kayla Alpert",
            "original_name": "Kayla Alpert",
            "popularity": 2.278,
            "profile_path": null,
            "credit_id": "602e011f0f3655003d2754f4",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 0,
            "id": 1516820,
            "known_for_department": "Production",
            "name": "Andrew Mittman",
            "original_name": "Andrew Mittman",
            "popularity": 0.844,
            "profile_path": null,
            "credit_id": "602e014687e63e003f94ef01",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 0,
            "id": 2058406,
            "known_for_department": "Production",
            "name": "Kevin Miserocchi",
            "original_name": "Kevin Miserocchi",
            "popularity": 0.84,
            "profile_path": null,
            "credit_id": "602e0154c3bffe003f354b00",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 21635,
            "known_for_department": "Production",
            "name": "Jonathan Glickman",
            "original_name": "Jonathan Glickman",
            "popularity": 1.22,
            "profile_path": null,
            "credit_id": "602e0162d940350040780b3a",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 1,
            "id": 1033779,
            "known_for_department": "Production",
            "name": "Gail Berman",
            "original_name": "Gail Berman",
            "popularity": 1.4,
            "profile_path": "/guvxCt4OjwQLyLuzsiNdH48stuc.jpg",
            "credit_id": "602e0176770700003d6c3930",
            "department": "Production",
            "job": "Executive Producer"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 69660,
            "known_for_department": "Writing",
            "name": "Charles Addams",
            "original_name": "Charles Addams",
            "popularity": 2.497,
            "profile_path": null,
            "credit_id": "61119db601e4d1007544d50a",
            "department": "Writing",
            "job": "Characters"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 6235,
            "known_for_department": "Art",
            "name": "Mark Scruton",
            "original_name": "Mark Scruton",
            "popularity": 0.62,
            "profile_path": null,
            "credit_id": "637e61b585b105008773f607",
            "department": "Art",
            "job": "Production Design"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 60408,
            "known_for_department": "Art",
            "name": "Adrian Curelea",
            "original_name": "Adrian Curelea",
            "popularity": 0.7,
            "profile_path": null,
            "credit_id": "637e61d3fa404600afd56526",
            "department": "Art",
            "job": "Supervising Art Director"
          },
          {
            "adult": false,
            "gender": 0,
            "id": 2081173,
            "known_for_department": "Art",
            "name": "Vlad Roseanu",
            "original_name": "Vlad Roseanu",
            "popularity": 0.972,
            "profile_path": null,
            "credit_id": "637e61f7a410c800848117d8",
            "department": "Art",
            "job": "Art Direction"
          },
          {
            "adult": false,
            "gender": 1,
            "id": 557,
            "known_for_department": "Costume & Make-Up",
            "name": "Colleen Atwood",
            "original_name": "Colleen Atwood",
            "popularity": 3.474,
            "profile_path": "/4hbAdhvoCkENdoFDLKdXck1ESIl.jpg",
            "credit_id": "637e622ca410c800d00a3803",
            "department": "Costume & Make-Up",
            "job": "Costume Design"
          },
          {
            "adult": false,
            "gender": 0,
            "id": 1338131,
            "known_for_department": "Sound",
            "name": "John Loranger",
            "original_name": "John Loranger",
            "popularity": 0.6,
            "profile_path": null,
            "credit_id": "637e6263514c4a0099989a01",
            "department": "Sound",
            "job": "Supervising Sound Editor"
          },
          {
            "adult": false,
            "gender": 0,
            "id": 2512946,
            "known_for_department": "Sound",
            "name": "Liviu Lupsa",
            "original_name": "Liviu Lupsa",
            "popularity": 0.732,
            "profile_path": null,
            "credit_id": "637e627bfa404600afd56547",
            "department": "Sound",
            "job": "Sound Mixer"
          },
          {
            "adult": false,
            "gender": 0,
            "id": 1699376,
            "known_for_department": "Visual Effects",
            "name": "Tom Turnbull",
            "original_name": "Tom Turnbull",
            "popularity": 0.728,
            "profile_path": null,
            "credit_id": "637e62b96e938a0084041d72",
            "department": "Visual Effects",
            "job": "Visual Effects Supervisor"
          },
          {
            "adult": false,
            "gender": 0,
            "id": 2128507,
            "known_for_department": "Editing",
            "name": "Razvan Ilinca",
            "original_name": "Razvan Ilinca",
            "popularity": 0.652,
            "profile_path": null,
            "credit_id": "637e62efa410c800d00a382e",
            "department": "Editing",
            "job": "Assistant Editor"
          },
          {
            "adult": false,
            "gender": 2,
            "id": 71268,
            "known_for_department": "Sound",
            "name": "Chris Bacon",
            "original_name": "Chris Bacon",
            "popularity": 0.665,
            "profile_path": null,
            "credit_id": "637e6317a410c800a4312b22",
            "department": "Crew",
            "job": "Additional Music"
          }
        ],
        "id": 119051
      
}];